// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClassroom = `-- name: CreateClassroom :one
INSERT INTO app.classrooms (code, type, floor, capacity)
VALUES ($1, $2, $3, $4)
RETURNING id, code, type, floor, capacity
`

type CreateClassroomParams struct {
	Code     string
	Type     AppModeType
	Floor    pgtype.Int2
	Capacity pgtype.Int2
}

type CreateClassroomRow struct {
	ID       int32
	Code     string
	Type     AppModeType
	Floor    pgtype.Int2
	Capacity pgtype.Int2
}

func (q *Queries) CreateClassroom(ctx context.Context, arg CreateClassroomParams) (CreateClassroomRow, error) {
	row := q.db.QueryRow(ctx, createClassroom,
		arg.Code,
		arg.Type,
		arg.Floor,
		arg.Capacity,
	)
	var i CreateClassroomRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Floor,
		&i.Capacity,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO app.courses
  (code, name, abbreviation, credits, color, type, id_career, id_course_theory, academic_year, id_teacher)
VALUES ($1, $2, $3, $4, $5, $6, (SELECT cr.id FROM app.careers cr WHERE cr.code = $7), $8, $9, $10)
RETURNING id, code, name
`

type CreateCourseParams struct {
	Code           string
	Name           string
	Abbreviation   string
	Credits        pgtype.Int2
	Color          string
	Type           AppModeType
	Code_2         string
	IDCourseTheory pgtype.Int4
	AcademicYear   int16
	IDTeacher      pgtype.Int4
}

type CreateCourseRow struct {
	ID   int32
	Code string
	Name string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CreateCourseRow, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Code,
		arg.Name,
		arg.Abbreviation,
		arg.Credits,
		arg.Color,
		arg.Type,
		arg.Code_2,
		arg.IDCourseTheory,
		arg.AcademicYear,
		arg.IDTeacher,
	)
	var i CreateCourseRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO app.groups (code, name, id_course, id_classroom)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name
`

type CreateGroupParams struct {
	Code        string
	Name        string
	IDCourse    int32
	IDClassroom pgtype.Int4
}

type CreateGroupRow struct {
	ID   int32
	Code string
	Name string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Code,
		arg.Name,
		arg.IDCourse,
		arg.IDClassroom,
	)
	var i CreateGroupRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const createGroupSession = `-- name: CreateGroupSession :exec
INSERT INTO app.schedule (id_group, day, start_hour_academic, duration_hours)
VALUES ($1, $2, $3, $4)
`

type CreateGroupSessionParams struct {
	IDGroup           int32
	Day               AppWeekDay
	StartHourAcademic int16
	DurationHours     int16
}

func (q *Queries) CreateGroupSession(ctx context.Context, arg CreateGroupSessionParams) error {
	_, err := q.db.Exec(ctx, createGroupSession,
		arg.IDGroup,
		arg.Day,
		arg.StartHourAcademic,
		arg.DurationHours,
	)
	return err
}

const createSharedTimetable = `-- name: CreateSharedTimetable :exec
INSERT INTO app.shared_timetables (id, selection)
VALUES ($1, $2::text::jsonb)
`

type CreateSharedTimetableParams struct {
	ID      string
	Column2 string
}

func (q *Queries) CreateSharedTimetable(ctx context.Context, arg CreateSharedTimetableParams) error {
	_, err := q.db.Exec(ctx, createSharedTimetable, arg.ID, arg.Column2)
	return err
}

const deleteClassroom = `-- name: DeleteClassroom :execrows
DELETE FROM app.classrooms WHERE id = $1
`

func (q *Queries) DeleteClassroom(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClassroom, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCourse = `-- name: DeleteCourse :execrows
DELETE FROM app.courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM app.groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGroupSessions = `-- name: DeleteGroupSessions :exec
DELETE FROM app.schedule WHERE id_group = $1
`

func (q *Queries) DeleteGroupSessions(ctx context.Context, idGroup int32) error {
	_, err := q.db.Exec(ctx, deleteGroupSessions, idGroup)
	return err
}

const deleteTeacher = `-- name: DeleteTeacher :execrows
DELETE FROM app.teachers WHERE id = $1
`

func (q *Queries) DeleteTeacher(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeacher, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClassroomType = `-- name: GetClassroomType :one
SELECT type FROM app.classrooms WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetClassroomType(ctx context.Context, id int32) (AppModeType, error) {
	row := q.db.QueryRow(ctx, getClassroomType, id)
	var type_ AppModeType
	err := row.Scan(&type_)
	return type_, err
}

const getCourseMeta = `-- name: GetCourseMeta :one
SELECT c.type, cr.code AS career_code
FROM app.courses c
JOIN app.careers cr ON cr.id = c.id_career
WHERE c.id = $1
`

type GetCourseMetaRow struct {
	Type       AppModeType
	CareerCode string
}

func (q *Queries) GetCourseMeta(ctx context.Context, id int32) (GetCourseMetaRow, error) {
	row := q.db.QueryRow(ctx, getCourseMeta, id)
	var i GetCourseMetaRow
	err := row.Scan(&i.Type, &i.CareerCode)
	return i, err
}

const getGroupMeta = `-- name: GetGroupMeta :one
SELECT g.id_course, c.type
FROM app.groups g
JOIN app.courses c ON c.id = g.id_course
WHERE g.id = $1
`

type GetGroupMetaRow struct {
	IDCourse int32
	Type     AppModeType
}

func (q *Queries) GetGroupMeta(ctx context.Context, id int32) (GetGroupMetaRow, error) {
	row := q.db.QueryRow(ctx, getGroupMeta, id)
	var i GetGroupMetaRow
	err := row.Scan(&i.IDCourse, &i.Type)
	return i, err
}

const getSharedTimetable = `-- name: GetSharedTimetable :one
SELECT selection FROM app.shared_timetables WHERE id = $1
`

func (q *Queries) GetSharedTimetable(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSharedTimetable, id)
	var selection []byte
	err := row.Scan(&selection)
	return selection, err
}

const getTheoryCourseMeta = `-- name: GetTheoryCourseMeta :one
SELECT c.type, cr.code AS career_code
FROM app.courses c
JOIN app.careers cr ON cr.id = c.id_career
WHERE c.id = $1
`

type GetTheoryCourseMetaRow struct {
	Type       AppModeType
	CareerCode string
}

func (q *Queries) GetTheoryCourseMeta(ctx context.Context, id int32) (GetTheoryCourseMetaRow, error) {
	row := q.db.QueryRow(ctx, getTheoryCourseMeta, id)
	var i GetTheoryCourseMetaRow
	err := row.Scan(&i.Type, &i.CareerCode)
	return i, err
}

const groupBelongsToCourse = `-- name: GroupBelongsToCourse :one
SELECT EXISTS(
  SELECT 1 FROM app.groups WHERE id = $1 AND id_course = $2
)
`

type GroupBelongsToCourseParams struct {
	ID       int32
	IDCourse int32
}

func (q *Queries) GroupBelongsToCourse(ctx context.Context, arg GroupBelongsToCourseParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupBelongsToCourse, arg.ID, arg.IDCourse)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkTeacherToCareer = `-- name: LinkTeacherToCareer :exec
INSERT INTO app.career_teachers (id_career, id_teacher)
SELECT cr.id, $2
FROM app.careers cr
WHERE cr.code = $1
ON CONFLICT DO NOTHING
`

type LinkTeacherToCareerParams struct {
	Code      string
	IDTeacher int32
}

func (q *Queries) LinkTeacherToCareer(ctx context.Context, arg LinkTeacherToCareerParams) error {
	_, err := q.db.Exec(ctx, linkTeacherToCareer, arg.Code, arg.IDTeacher)
	return err
}

const listClassrooms = `-- name: ListClassrooms :many
SELECT id, code, type, floor, capacity
FROM app.classrooms
ORDER BY code
`

type ListClassroomsRow struct {
	ID       int32
	Code     string
	Type     AppModeType
	Floor    pgtype.Int2
	Capacity pgtype.Int2
}

func (q *Queries) ListClassrooms(ctx context.Context) ([]ListClassroomsRow, error) {
	rows, err := q.db.Query(ctx, listClassrooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassroomsRow
	for rows.Next() {
		var i ListClassroomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Floor,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
SELECT t.id, t.name, t.last_name
FROM app.teachers t
JOIN app.career_teachers ct ON ct.id_teacher = t.id
JOIN app.careers cr ON cr.id = ct.id_career
WHERE cr.code = $1
ORDER BY t.last_name, t.name
`

type ListTeachersRow struct {
	ID       int32
	Name     string
	LastName string
}

func (q *Queries) ListTeachers(ctx context.Context, code string) ([]ListTeachersRow, error) {
	rows, err := q.db.Query(ctx, listTeachers, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeachersRow
	for rows.Next() {
		var i ListTeachersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassroom = `-- name: UpdateClassroom :one
UPDATE app.classrooms
SET code = $2, type = $3, floor = $4, capacity = $5
WHERE id = $1
RETURNING id, code, type, floor, capacity
`

type UpdateClassroomParams struct {
	ID       int32
	Code     string
	Type     AppModeType
	Floor    pgtype.Int2
	Capacity pgtype.Int2
}

type UpdateClassroomRow struct {
	ID       int32
	Code     string
	Type     AppModeType
	Floor    pgtype.Int2
	Capacity pgtype.Int2
}

func (q *Queries) UpdateClassroom(ctx context.Context, arg UpdateClassroomParams) (UpdateClassroomRow, error) {
	row := q.db.QueryRow(ctx, updateClassroom,
		arg.ID,
		arg.Code,
		arg.Type,
		arg.Floor,
		arg.Capacity,
	)
	var i UpdateClassroomRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Floor,
		&i.Capacity,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE app.courses
SET code = $2,
    name = $3,
    abbreviation = $4,
    credits = $5,
    color = $6,
    id_course_theory = $7,
    academic_year = $8,
    id_teacher = $9
WHERE id = $1
RETURNING id, code, name
`

type UpdateCourseParams struct {
	ID             int32
	Code           string
	Name           string
	Abbreviation   string
	Credits        pgtype.Int2
	Color          string
	IDCourseTheory pgtype.Int4
	AcademicYear   int16
	IDTeacher      pgtype.Int4
}

type UpdateCourseRow struct {
	ID   int32
	Code string
	Name string
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (UpdateCourseRow, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Abbreviation,
		arg.Credits,
		arg.Color,
		arg.IDCourseTheory,
		arg.AcademicYear,
		arg.IDTeacher,
	)
	var i UpdateCourseRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE app.groups
SET code = $2, name = $3, id_classroom = $4
WHERE id = $1
RETURNING id, code, name
`

type UpdateGroupParams struct {
	ID          int32
	Code        string
	Name        string
	IDClassroom pgtype.Int4
}

type UpdateGroupRow struct {
	ID   int32
	Code string
	Name string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UpdateGroupRow, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.IDClassroom,
	)
	var i UpdateGroupRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const updateTeacher = `-- name: UpdateTeacher :one
UPDATE app.teachers
SET name = $2, last_name = $3
WHERE id = $1
RETURNING id, name, last_name
`

type UpdateTeacherParams struct {
	ID       int32
	Name     string
	LastName string
}

type UpdateTeacherRow struct {
	ID       int32
	Name     string
	LastName string
}

func (q *Queries) UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (UpdateTeacherRow, error) {
	row := q.db.QueryRow(ctx, updateTeacher, arg.ID, arg.Name, arg.LastName)
	var i UpdateTeacherRow
	err := row.Scan(&i.ID, &i.Name, &i.LastName)
	return i, err
}

const upsertTeacher = `-- name: UpsertTeacher :one
INSERT INTO app.teachers (name, last_name)
VALUES ($1, $2)
ON CONFLICT (name, last_name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertTeacherParams struct {
	Name     string
	LastName string
}

func (q *Queries) UpsertTeacher(ctx context.Context, arg UpsertTeacherParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertTeacher, arg.Name, arg.LastName)
	var id int32
	err := row.Scan(&id)
	return id, err
}
