// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppModeType string

const (
	AppModeTypeTHEORY     AppModeType = "THEORY"
	AppModeTypeLABORATORY AppModeType = "LABORATORY"
)

func (e *AppModeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppModeType(s)
	case string:
		*e = AppModeType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppModeType: %T", src)
	}
	return nil
}

type NullAppModeType struct {
	AppModeType AppModeType
	Valid       bool // Valid is true if AppModeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppModeType) Scan(value interface{}) error {
	if value == nil {
		ns.AppModeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppModeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppModeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppModeType), nil
}

type AppUserRole string

const (
	AppUserRoleADMIN AppUserRole = "ADMIN"
	AppUserRoleUSER  AppUserRole = "USER"
)

func (e *AppUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppUserRole(s)
	case string:
		*e = AppUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppUserRole: %T", src)
	}
	return nil
}

type NullAppUserRole struct {
	AppUserRole AppUserRole
	Valid       bool // Valid is true if AppUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppUserRole), nil
}

type AppWeekDay string

const (
	AppWeekDayMONDAY    AppWeekDay = "MONDAY"
	AppWeekDayTUESDAY   AppWeekDay = "TUESDAY"
	AppWeekDayWEDNESDAY AppWeekDay = "WEDNESDAY"
	AppWeekDayTHURSDAY  AppWeekDay = "THURSDAY"
	AppWeekDayFRIDAY    AppWeekDay = "FRIDAY"
	AppWeekDaySATURDAY  AppWeekDay = "SATURDAY"
)

func (e *AppWeekDay) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppWeekDay(s)
	case string:
		*e = AppWeekDay(s)
	default:
		return fmt.Errorf("unsupported scan type for AppWeekDay: %T", src)
	}
	return nil
}

type NullAppWeekDay struct {
	AppWeekDay AppWeekDay
	Valid      bool // Valid is true if AppWeekDay is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppWeekDay) Scan(value interface{}) error {
	if value == nil {
		ns.AppWeekDay, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppWeekDay.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppWeekDay) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppWeekDay), nil
}

type AppAcademicHour struct {
	HourNumber int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
}

type AppCareer struct {
	ID        int32
	Code      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type AppCareerAvailableHour struct {
	IDCareer   int32
	HourNumber int16
	CreatedAt  pgtype.Timestamptz
}

type AppCareerTeacher struct {
	IDCareer  int32
	IDTeacher int32
	CreatedAt pgtype.Timestamptz
}

type AppClassroom struct {
	ID        int32
	Code      string
	Type      AppModeType
	Floor     pgtype.Int2
	Capacity  pgtype.Int2
	CreatedAt pgtype.Timestamptz
}

type AppCourse struct {
	ID             int32
	Code           string
	Name           string
	Abbreviation   string
	Summary        string
	Credits        int16
	Color          string
	Type           AppModeType
	IDCareer       int32
	IDCourseTheory pgtype.Int4
	AcademicYear   int16
	IDTeacher      pgtype.Int4
	CreatedAt      pgtype.Timestamptz
}

type AppGroup struct {
	ID          int32
	Code        string
	Name        string
	IDCourse    int32
	IDClassroom pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

type AppSchedule struct {
	ID                int32
	IDGroup           int32
	Day               AppWeekDay
	StartHourAcademic int16
	DurationHours     int16
	CreatedAt         pgtype.Timestamptz
}

type AppTeacher struct {
	ID        int32
	Name      string
	LastName  string
	CreatedAt pgtype.Timestamptz
}

type AppUser struct {
	ID          int32
	Email       string
	DisplayName string
	Role        AppUserRole
	CreatedAt   pgtype.Timestamptz
}
