// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAcademicHours = `-- name: ListAcademicHours :many
SELECT hour_number, start_time, end_time
FROM app.academic_hours
ORDER BY hour_number
`

func (q *Queries) ListAcademicHours(ctx context.Context) ([]AppAcademicHour, error) {
	rows, err := q.db.Query(ctx, listAcademicHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppAcademicHour
	for rows.Next() {
		var i AppAcademicHour
		if err := rows.Scan(&i.HourNumber, &i.StartTime, &i.EndTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannerCourses = `-- name: ListPlannerCourses :many
SELECT c.id, c.code, c.name, c.abbreviation, c.summary, c.credits, c.color, c.type,
       c.academic_year, c.id_course_theory, t.id AS teacher_id,
       CAST(COALESCE(t.name || ' ' || t.last_name, '') AS text) AS teacher_name
FROM app.courses c
JOIN app.careers cr ON cr.id = c.id_career
LEFT JOIN app.teachers t ON t.id = c.id_teacher
WHERE cr.code = $1
ORDER BY c.academic_year, c.name, c.type
`

type ListPlannerCoursesRow struct {
	ID             int32
	Code           string
	Name           string
	Abbreviation   string
	Summary        string
	Credits        pgtype.Int2
	Color          string
	Type           AppModeType
	AcademicYear   int16
	IDCourseTheory pgtype.Int4
	TeacherID      pgtype.Int4
	TeacherName    string
}

func (q *Queries) ListPlannerCourses(ctx context.Context, code string) ([]ListPlannerCoursesRow, error) {
	rows, err := q.db.Query(ctx, listPlannerCourses, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlannerCoursesRow
	for rows.Next() {
		var i ListPlannerCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Abbreviation,
			&i.Summary,
			&i.Credits,
			&i.Color,
			&i.Type,
			&i.AcademicYear,
			&i.IDCourseTheory,
			&i.TeacherID,
			&i.TeacherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannerGroups = `-- name: ListPlannerGroups :many
SELECT g.id, g.id_course, g.name, cl.code AS classroom_code
FROM app.groups g
JOIN app.courses c ON c.id = g.id_course
JOIN app.careers cr ON cr.id = c.id_career
LEFT JOIN app.classrooms cl ON cl.id = g.id_classroom
WHERE cr.code = $1
ORDER BY g.name
`

type ListPlannerGroupsRow struct {
	ID            int32
	IDCourse      int32
	Name          string
	ClassroomCode pgtype.Text
}

func (q *Queries) ListPlannerGroups(ctx context.Context, code string) ([]ListPlannerGroupsRow, error) {
	rows, err := q.db.Query(ctx, listPlannerGroups, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlannerGroupsRow
	for rows.Next() {
		var i ListPlannerGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.IDCourse,
			&i.Name,
			&i.ClassroomCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannerSessions = `-- name: ListPlannerSessions :many
SELECT s.id, s.id_group, g.id_course, s.day, s.start_hour_academic, s.duration_hours,
       c.type, c.name AS course_name, cl.code AS classroom_code
FROM app.schedule s
JOIN app.groups g ON g.id = s.id_group
JOIN app.courses c ON c.id = g.id_course
JOIN app.careers cr ON cr.id = c.id_career
LEFT JOIN app.classrooms cl ON cl.id = g.id_classroom
WHERE cr.code = $1
ORDER BY s.day, s.start_hour_academic
`

type ListPlannerSessionsRow struct {
	ID                int32
	IDGroup           int32
	IDCourse          int32
	Day               AppWeekDay
	StartHourAcademic int16
	DurationHours     int16
	Type              AppModeType
	CourseName        string
	ClassroomCode     pgtype.Text
}

func (q *Queries) ListPlannerSessions(ctx context.Context, code string) ([]ListPlannerSessionsRow, error) {
	rows, err := q.db.Query(ctx, listPlannerSessions, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlannerSessionsRow
	for rows.Next() {
		var i ListPlannerSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.IDGroup,
			&i.IDCourse,
			&i.Day,
			&i.StartHourAcademic,
			&i.DurationHours,
			&i.Type,
			&i.CourseName,
			&i.ClassroomCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
