-- ponytail: one-time bootstrap schema; add migrations after the first deployed change.
BEGIN;

CREATE SCHEMA app;

CREATE TYPE app.mode_type AS ENUM ('THEORY', 'LABORATORY');
CREATE TYPE app.week_day AS ENUM (
  'MONDAY',
  'TUESDAY',
  'WEDNESDAY',
  'THURSDAY',
  'FRIDAY',
  'SATURDAY'
);

CREATE TABLE app.careers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE app.academic_hours (
  hour_number SMALLINT PRIMARY KEY CHECK (hour_number BETWEEN 1 AND 15),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  CHECK (end_time > start_time)
);

INSERT INTO app.academic_hours (hour_number, start_time, end_time) VALUES
  (1,  '07:00', '07:50'),
  (2,  '07:50', '08:50'),
  (3,  '08:50', '09:40'),
  (4,  '09:40', '10:30'),
  (5,  '10:40', '11:30'),
  (6,  '11:30', '12:20'),
  (7,  '12:20', '13:10'),
  (8,  '13:10', '14:00'),
  (9,  '14:00', '14:50'),
  (10, '14:50', '15:40'),
  (11, '15:50', '16:40'),
  (12, '16:40', '17:30'),
  (13, '17:40', '18:30'),
  (14, '18:30', '19:20'),
  (15, '19:20', '20:10');

CREATE TABLE app.career_available_hours (
  id_career INTEGER NOT NULL REFERENCES app.careers(id) ON DELETE CASCADE,
  hour_number SMALLINT NOT NULL REFERENCES app.academic_hours(hour_number) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id_career, hour_number)
);

CREATE TABLE app.teachers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (name, last_name)
);

CREATE TABLE app.career_teachers (
  id_career INTEGER NOT NULL REFERENCES app.careers(id) ON DELETE CASCADE,
  id_teacher INTEGER NOT NULL REFERENCES app.teachers(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id_career, id_teacher)
);

CREATE TABLE app.classrooms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(10) NOT NULL,
  type app.mode_type NOT NULL,
  floor SMALLINT,
  capacity SMALLINT CHECK (capacity > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (code, type)
);

CREATE TABLE app.courses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(24) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  abbreviation VARCHAR(10) NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  credits SMALLINT NOT NULL CHECK (credits > 0),
  color VARCHAR(7) NOT NULL CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
  type app.mode_type NOT NULL,
  id_career INTEGER NOT NULL REFERENCES app.careers(id) ON DELETE CASCADE,
  id_course_theory INTEGER REFERENCES app.courses(id) ON DELETE RESTRICT,
  academic_year SMALLINT NOT NULL CHECK (academic_year BETWEEN 1 AND 5),
  id_teacher INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (id_career, name, abbreviation),
  FOREIGN KEY (id_career, id_teacher)
    REFERENCES app.career_teachers(id_career, id_teacher),
  CHECK (id_course_theory IS NULL OR id_course_theory <> id),
  CHECK (
    (type = 'LABORATORY' AND id_course_theory IS NOT NULL) OR
    (type = 'THEORY' AND id_course_theory IS NULL)
  )
);

CREATE TABLE app.groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(24) NOT NULL UNIQUE,
  name VARCHAR(10) NOT NULL,
  id_course INTEGER NOT NULL REFERENCES app.courses(id) ON DELETE CASCADE,
  id_classroom INTEGER REFERENCES app.classrooms(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (id_course, name)
);

CREATE TABLE app.schedule (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_group INTEGER NOT NULL REFERENCES app.groups(id) ON DELETE CASCADE,
  day app.week_day NOT NULL,
  start_hour_academic SMALLINT NOT NULL
    REFERENCES app.academic_hours(hour_number) ON DELETE RESTRICT,
  duration_hours SMALLINT NOT NULL CHECK (duration_hours BETWEEN 1 AND 4),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (id_group, day, start_hour_academic),
  CHECK (start_hour_academic + duration_hours <= 16)
);

CREATE INDEX career_available_hours_hour_idx
  ON app.career_available_hours(hour_number);
CREATE INDEX career_teachers_teacher_idx ON app.career_teachers(id_teacher);
CREATE INDEX courses_career_idx ON app.courses(id_career);
CREATE INDEX courses_teacher_idx ON app.courses(id_teacher);
CREATE INDEX courses_theory_idx ON app.courses(id_course_theory);
CREATE INDEX courses_academic_year_idx ON app.courses(academic_year);
CREATE INDEX groups_classroom_idx ON app.groups(id_classroom);
CREATE INDEX schedule_start_hour_idx ON app.schedule(start_hour_academic);

-- ponytail: exact duplicates are blocked; add overlap constraints when writes exist.
COMMIT;
