// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app.users (email, display_name)
VALUES ($1, $2)
RETURNING id, email, display_name, role
`

type CreateUserParams struct {
	Email       string
	DisplayName string
}

type CreateUserRow struct {
	ID          int32
	Email       string
	DisplayName string
	Role        AppUserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, role
FROM app.users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID          int32
	Email       string
	DisplayName string
	Role        AppUserRole
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, role
FROM app.users
ORDER BY created_at DESC, id DESC
`

type ListUsersRow struct {
	ID          int32
	Email       string
	DisplayName string
	Role        AppUserRole
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdminUser = `-- name: UpsertAdminUser :one
INSERT INTO app.users (email, display_name, role)
VALUES ($1, $2, 'ADMIN')
ON CONFLICT (email) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  role = 'ADMIN'
RETURNING id, email, display_name, role
`

type UpsertAdminUserParams struct {
	Email       string
	DisplayName string
}

type UpsertAdminUserRow struct {
	ID          int32
	Email       string
	DisplayName string
	Role        AppUserRole
}

func (q *Queries) UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) (UpsertAdminUserRow, error) {
	row := q.db.QueryRow(ctx, upsertAdminUser, arg.Email, arg.DisplayName)
	var i UpsertAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
	)
	return i, err
}
