-- ponytail: one-shot migration for databases already created from schema.sql.
BEGIN;

CREATE TYPE app.user_role AS ENUM ('ADMIN', 'USER');

CREATE TABLE app.users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(320) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  role app.user_role NOT NULL DEFAULT 'USER',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CHECK (email = lower(email) AND position('@' in email) > 1),
  CHECK (btrim(display_name) <> '')
);

COMMIT;
