// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: academic_hours.sql

package database

import (
	"context"
)

const countAcademicHours = `-- name: CountAcademicHours :one
SELECT COUNT(*) FROM academic_hours
`

func (q *Queries) CountAcademicHours(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAcademicHours)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seedAcademicHours = `-- name: SeedAcademicHours :exec
INSERT INTO academic_hours (hour_number, start_time, end_time) VALUES
(1,  '07:00', '07:50'),
(2,  '07:50', '08:50'),
(3,  '08:50', '09:40'),
(4,  '09:40', '10:30'),
(5,  '10:40', '11:30'),
(6,  '11:30', '12:20'),
(7,  '12:20', '13:10'),
(8,  '13:10', '14:00'),
(9,  '14:00', '14:50'),
(10, '14:50', '15:40'),
(11, '15:50', '16:40'),
(12, '16:40', '17:30'),
(13, '17:40', '18:30'),
(14, '18:30', '19:20'),
(15, '19:20', '20:10')
`

func (q *Queries) SeedAcademicHours(ctx context.Context) error {
	_, err := q.db.Exec(ctx, seedAcademicHours)
	return err
}
