// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ModeType string

const (
	ModeTypeTHEORY     ModeType = "THEORY"
	ModeTypeLABORATORY ModeType = "LABORATORY"
)

func (e *ModeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModeType(s)
	case string:
		*e = ModeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ModeType: %T", src)
	}
	return nil
}

type NullModeType struct {
	ModeType ModeType
	Valid    bool // Valid is true if ModeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModeType) Scan(value interface{}) error {
	if value == nil {
		ns.ModeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModeType), nil
}

type WeekDay string

const (
	WeekDayMONDAY    WeekDay = "MONDAY"
	WeekDayTUESDAY   WeekDay = "TUESDAY"
	WeekDayWEDNESDAY WeekDay = "WEDNESDAY"
	WeekDayTHURSDAY  WeekDay = "THURSDAY"
	WeekDayFRIDAY    WeekDay = "FRIDAY"
	WeekDaySATURDAY  WeekDay = "SATURDAY"
)

func (e *WeekDay) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WeekDay(s)
	case string:
		*e = WeekDay(s)
	default:
		return fmt.Errorf("unsupported scan type for WeekDay: %T", src)
	}
	return nil
}

type NullWeekDay struct {
	WeekDay WeekDay
	Valid   bool // Valid is true if WeekDay is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWeekDay) Scan(value interface{}) error {
	if value == nil {
		ns.WeekDay, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WeekDay.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWeekDay) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WeekDay), nil
}

type AcademicHour struct {
	HourNumber int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
}

type Classroom struct {
	ID        int32
	Code      string
	Type      ModeType
	Floor     pgtype.Int2
	Capacity  pgtype.Int2
	CreatedAt pgtype.Timestamptz
}

type Course struct {
	ID             int32
	Code           string
	Name           string
	Abbreviation   string
	Color          string
	Type           ModeType
	IDCourseTheory pgtype.Int4
	AcademicYear   int16
	IDTeacher      pgtype.Int4
	CreatedAt      pgtype.Timestamptz
}

type Group struct {
	ID          int32
	Code        string
	Name        string
	IDCourse    int32
	IDClassroom pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

type Schedule struct {
	ID                int32
	IDGroup           int32
	Day               WeekDay
	StartHourAcademic int16
	DurationHours     int16
	CreatedAt         pgtype.Timestamptz
}

type Teacher struct {
	ID        int32
	Name      string
	LastName  string
	CreatedAt pgtype.Timestamptz
}
